// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB08HAw5M8Wdy7p7i6V9bLoSZwxG_oqI4',
    appId: '1:875096058378:android:b30e8fffc47e4b877a4df3',
    messagingSenderId: '875096058378',
    projectId: 'fruit-hup-7a18d',
    storageBucket: 'fruit-hup-7a18d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABpycg0KKnyXTFcAz3xr08Bdz1aYOsSL0',
    appId: '1:875096058378:ios:dc7cfb2624a55fe47a4df3',
    messagingSenderId: '875096058378',
    projectId: 'fruit-hup-7a18d',
    storageBucket: 'fruit-hup-7a18d.firebasestorage.app',
    androidClientId: '875096058378-65katcl6cj0nutbpgrns8k6k4o2e8sup.apps.googleusercontent.com',
    iosClientId: '875096058378-06i1smvruch14pv54e5eq5427ihf8dbr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsApp',
  );
}
